on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, windows ]
  pull_request:
    branches: [ main, windows ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:
       include:
         - SBCL_VERSION: 2.3.2
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2
        with:
          install: make unzip
      - name: download SBCL
        run: wget https://downloads.sourceforge.net/project/sbcl/sbcl/${{ matrix.SBCL_VERSION }}/sbcl-${{ matrix.SBCL_VERSION }}-x86-64-windows-binary.msi
      - name: install SBCL
        # for unknown reason, msiexec pops up a window under msys2, so use cmd instead
        shell: cmd
        run: msiexec /a sbcl-${{ matrix.SBCL_VERSION }}-x86-64-windows-binary.msi TARGETDIR=C:\sbcl /qn
      - uses: actions/checkout@v3
      - name: Build and Install
        run: |
          dir c:\sbcl\PFiles\"Steel Bank Common Lisp"
          c:\sbcl\Pfiles\"Steel Bank Common Lisp"\sbcl.exe --eval "(progn (print \"Hello\") (terpri) (quit))"
          dir
          c:\sbcl\Pfiles\"Steel Bank Common Lisp"\sbcl.exe --load setup.lisp
          dir
          %UserProfile%\AppData\Local\ocicl\ocicl.exe setup
        shell: cmd
